"""Render the tool catalog, per-agent registry pages, and generated contract tests."""
from __future__ import annotations

import sys
from pathlib import Path

from swarm.tool_registry import ERROR_STATES, ROOT, iter_entries, load_document, validate_registry

DOCS_HEADER = "<!-- generated by python3 -m swarm.tool_registry docs; do not edit -->"
SECTIONS = (
    "## Identity and mission",
    "## Inputs, outputs, and handoffs",
    "## Lane tools",
    "## Shared tools",
    "## ACP profile",
    "## Degradation",
)
CATALOG = "docs/tools/catalog.md"
CONTRACT_TESTS = "tests/generated/test_tool_contracts.py"


def write_docs(*, check: bool, path: Path | None = None, root: Path | None = None) -> int:
    root = root or ROOT
    if not _registry_ok(path):
        return 1
    rendered = render_docs(load_document(path))
    return _emit(rendered, root, check, "tool docs")


def write_contract_tests(*, check: bool, path: Path | None = None, root: Path | None = None) -> int:
    root = root or ROOT
    if not _registry_ok(path):
        return 1
    text = render_contract_tests(load_document(path))
    return _emit({CONTRACT_TESTS: text}, root, check, "tool contract tests")


def _registry_ok(path: Path | None) -> bool:
    errors = validate_registry(path)
    if errors:
        print("\n".join(errors), file=sys.stderr)
        return False
    return True


def render_docs(data: dict) -> dict[str, str]:
    agents = [a for a in data.get("agents") or [] if isinstance(a, dict)]
    lane: dict[str, list[dict]] = {a["id"]: [] for a in agents}
    shared: list[dict] = []
    for container, tool in iter_entries(data):
        if not isinstance(tool, dict):
            continue
        if container == "shared":
            shared.append(tool)
        elif container in lane:
            lane[container].append(tool)
    shared.sort(key=lambda tool: tool.get("name") or "")
    pages: dict[str, str] = {}
    for agent in agents:
        tools = sorted(lane[agent["id"]], key=lambda tool: tool.get("name") or "")
        used = [tool for tool in shared if agent["id"] in (tool.get("permitted_callers") or [])]
        rel = f"docs/tools/agents/{agent['slug']}.md"
        pages[rel] = _agent_page(agent, tools, used)
    pages[CATALOG] = _catalog(agents, lane, shared)
    return pages


def render_contract_tests(data: dict) -> str:
    tools = [tool for _container, tool in iter_entries(data) if isinstance(tool, dict) and tool.get("name")]
    tools.sort(key=lambda tool: tool["name"])
    lines = [
        '"""Generated by python3 -m swarm.tool_registry gen-tests. Do not edit."""',
        "from swarm.tool_registry import call_tool",
        "",
        "",
        "def test_unregistered_name_is_not_callable():",
        '    result = call_tool("__not_registered__", "A01", {})',
        '    assert result["state"] == "INVALID_INPUT"',
        '    assert result["field"] == "name"',
    ]
    for tool in tools:
        name = tool["name"]
        caller = tool["permitted_callers"][0]
        examples = tool["examples"]
        lines.extend(["", "", f"def test_{name}_success():",
                      f"    result = call_tool({name!r}, {caller!r}, {examples['success']!r})",
                      '    assert result["state"] == "SUCCESS"',
                      "", "", f"def test_{name}_invalid_input():",
                      f"    result = call_tool({name!r}, {caller!r}, {examples['invalid_input']!r})",
                      '    assert result["state"] == "INVALID_INPUT"',
                      '    assert result["field"]',
                      "", "", f"def test_{name}_unauthorized():",
                      f"    result = call_tool({name!r}, {examples['unauthorized_caller']!r}, {examples['success']!r})",
                      '    assert result["state"] == "UNAUTHORIZED"',
                      f"    assert result['caller'] == {examples['unauthorized_caller']!r}",
                      f"    assert result['target'] == {name!r}",
                      "", "", f"def test_{name}_dependency():",
                      f"    result = call_tool({name!r}, {caller!r}, {examples['dependency']!r})",
                      '    assert result["state"] == "DEPENDENCY_UNAVAILABLE"',
                      "", "", f"def test_{name}_timeout():",
                      f"    result = call_tool({name!r}, {caller!r}, {examples['timeout']!r}, timeout_s=0.05)",
                      '    assert result["state"] == "TIMEOUT"',
                      "", "", f"def test_{name}_partial():",
                      f"    result = call_tool({name!r}, {caller!r}, {examples['partial']!r})",
                      '    assert result["state"] == "PARTIAL_SUCCESS"',
                      '    assert isinstance(result["completed_fraction"], (int, float))'])
    lines.append("")
    return "\n".join(lines)


def _emit(files: dict[str, str], root: Path, check: bool, label: str) -> int:
    drifted = []
    for rel, text in files.items():
        dest = root / rel
        if check:
            current = dest.read_text(encoding="utf-8") if dest.is_file() else None
            if current != text:
                drifted.append(rel)
        else:
            dest.parent.mkdir(parents=True, exist_ok=True)
            dest.write_text(text, encoding="utf-8")
    if drifted:
        print(f"{label} drift:\n" + "\n".join(drifted), file=sys.stderr)
        return 1
    if check:
        print(f"{label} ok")
    return 0


def _agent_page(agent: dict, lane_tools: list[dict], shared_used: list[dict]) -> str:
    caps = ", ".join(f"`{item}`" for item in agent["capabilities"])
    consumes = ", ".join(f"`{item}`" for item in agent["consumes"])
    produces = ", ".join(f"`{item}`" for item in agent["produces"])
    lines = [
        DOCS_HEADER,
        "",
        f"# {agent['id']} — {agent['name']}",
        "",
        "## Identity and mission",
        "",
        f"- Id: `{agent['id']}`",
        f"- Code: `{agent['code']}`",
        f"- Slug: `{agent['slug']}`",
        f"- Class: `{agent['class']}`",
        f"- Lane: `{agent['lane']}`",
        "",
        agent["description"],
        "",
        f"Capabilities: {caps}.",
        "",
        "## Inputs, outputs, and handoffs",
        "",
        f"Consumes: {consumes}.",
        "",
        f"Produces: {produces}.",
        "",
        "## Lane tools",
        "",
        _tool_table(lane_tools, "No lane tools are registered."),
        "",
        "## Shared tools",
        "",
        _tool_table(shared_used, "This agent has no shared tools."),
        "",
        "## ACP profile",
        "",
        "Routing and the permission matrix come from this registry via `swarm/acp.py` (`acp.v1`).",
        f"Endpoint: `inproc://{agent['id']}`.",
        "A message is delivered only when this agent produces the type and the peer consumes it, or the reverse. Anything else is UNAUTHORIZED and is written to the bus audit log with caller, target, and reason.",
        "",
        "## Degradation",
        "",
        "Registered lane tools run in-process through the registry call path. They do not consult the peer circuit breaker.",
        "A peer that times out is retried with capped exponential backoff, then DEAD_LETTERED with the full envelope.",
        "INVALID_INPUT and UNAUTHORIZED are not retried. A peer that fails repeatedly is circuit-broken; later calls fail immediately while local tools still run.",
        "",
    ]
    return "\n".join(lines)


def _catalog(agents: list[dict], lane: dict[str, list[dict]], shared: list[dict]) -> str:
    rows = []
    for agent in agents:
        for tool in sorted(lane[agent["id"]], key=lambda item: item.get("name") or ""):
            rows.append(tool)
    rows.extend(shared)
    rows.sort(key=lambda tool: tool.get("name") or "")
    lines = [
        DOCS_HEADER,
        "",
        "# Tool catalog",
        "",
        f"Registered tools: {len(rows)}. Shared tools: {len(shared)}.",
        "",
        "| Name | Owner | Category | Purpose | Permitted callers | Contract test |",
        "| --- | --- | --- | --- | --- | --- |",
    ]
    if rows:
        for tool in rows:
            callers = ", ".join(tool.get("permitted_callers") or [])
            category = "shared" if tool.get("owner") == "shared" else "lane"
            lines.append(
                f"| `{tool['name']}` | {tool['owner']} | {category} | {tool['purpose']} | {callers} | `{CONTRACT_TESTS}` |"
            )
    else:
        lines.append("| — | — | — | No tools are registered. | — | — |")
    lines.extend(["", "## By category", "", "### lane", ""])
    lane_rows = [tool for tool in rows if tool.get("owner") != "shared"]
    shared_rows = [tool for tool in rows if tool.get("owner") == "shared"]
    lines.extend(_name_list(lane_rows, "No lane tools are registered."))
    lines.extend(["", "### shared", ""])
    lines.extend(_name_list(shared_rows, "No shared tools are registered."))
    lines.extend(["", "## By agent", ""])
    for agent in agents:
        used = [tool for tool in shared if agent["id"] in (tool.get("permitted_callers") or [])]
        lines.append(f"### {agent['id']} `{agent['slug']}`")
        lines.append("")
        lines.extend(_name_list(lane[agent["id"]], "No lane tools."))
        if used:
            lines.append("")
            lines.append("Shared: " + ", ".join(f"`{tool['name']}`" for tool in used) + ".")
        lines.append("")
    lines.extend(["## Agents", "", "| Agent | Lane tools | Shared tools used |", "| --- | --- | --- |"])
    for agent in agents:
        used_n = sum(1 for tool in shared if agent["id"] in (tool.get("permitted_callers") or []))
        lines.append(f"| {agent['id']} `{agent['slug']}` | {len(lane[agent['id']])} | {used_n} |")
    lines.append("")
    return "\n".join(lines)


def _name_list(tools: list[dict], empty: str) -> list[str]:
    if not tools:
        return [empty]
    return [f"- `{tool['name']}` ({tool.get('owner')})" for tool in tools]


def _tool_table(tools: list[dict], empty: str) -> str:
    if not tools:
        return empty
    lines = [
        "| Name | Purpose | Input | Output | Failure modes | Timeout (s) | Idempotency | Permitted callers |",
        "| --- | --- | --- | --- | --- | --- | --- | --- |",
    ]
    for tool in tools:
        modes = ", ".join(state for state in ERROR_STATES if state in (tool.get("errors") or []))
        callers = ", ".join(tool.get("permitted_callers") or [])
        timeout = tool.get("timeout_s")
        lines.append(
            "| "
            + " | ".join([
                f"`{tool['name']}`",
                str(tool.get("purpose") or ""),
                _io_summary(tool.get("input_schema") or {}),
                _io_summary(tool.get("output_schema") or {}),
                modes,
                str(timeout),
                str(tool.get("idempotency") or ""),
                callers,
            ])
            + " |"
        )
    return "\n".join(lines)


def _io_summary(schema: dict) -> str:
    props = schema.get("properties") or {}
    required = set(schema.get("required") or [])
    if not isinstance(props, dict) or not props:
        return "none"
    parts = []
    for key, spec in props.items():
        if not isinstance(spec, dict):
            continue
        typ = spec.get("type", "const" if "const" in spec else "any")
        mark = "" if key in required else "?"
        parts.append(f"`{key}`{mark}: {typ}")
    return ", ".join(parts) if parts else "none"
